#!/bin/bash

## Execute this file using qsub command:  qsub qsleep

#$ -V                             # Inherit the submission environment
#$ -cwd                           # Start job in submission dir
#$ -N sleep                       # Job name
#$ -j y                           # Combine stderr and stdout into stdout
#$ -o $JOB_NAME-$JOB_ID           # Name of the output file
#$ -e $JOB_NAME-$JOB_ID.err       # Name of the stderr file
#$ -pe 1way 8                     # 8 cores/node on Longhorn
#$ -q development                      # Queue name
#$ -P gpgpu                       # project type
#$ -l h_rt=1:00:00                # runtime (hh:mm:ss) - 2 hours max

hostname

sleep 3600
